### ISSUE TITLE
Map Functions/ GUI Pathways Update/Function Question

### ISSUE THREAD

**Issue by Rishbob** [SlothfulAlfred/Air-Pollution-App-CS#21]
I tried to get gui.py to find regional_map.py, but it seemed to have issues. Does anyone know if classes and functions have different import commands?

Additionally, we need to update the file pathways for the images, since they are now in a unique folder.

Lastly,  given that we are considering deleting the maps generated when the user leaves the page, I'm going to add a dedicated function that clears the maps folder of all images. However, if anyone knows of a way to do this without a dedicated function, I'd appreciate it.

**Comment by johannzhao** [comment]
Will do the file pathway with you after school

**Comment by Rishbob** [comment]
i'm good for 7-8

**Comment by SlothfulAlfred** [comment]
- First of all, in `gui.py` you're not even importing the module `regional_map.py` nor does there exist a module called `regional_map.py` to begin with. However, you do have this in your imports in `gui.py`:
```
from tkinter import *
from tkinter import messagebox
import tkinter as tk
```
Why are you importing tkinter three different times? The line `from tkinter import *` already imports all the things inside of tkinter so you do not need `import tkinter as tk` and I'm pretty sure you also do not need `from tkinter import messagebox`. Classes and functions are exactly the same as importing any module, in fact, do you not realize that pretty much everything that you import is a class or a function? Did you not also import the `Country` class in some of your other files; did you do anything differently then??

- Next, the file paths in `gui.py` are still not relative. You need to fix those ASAP and uncheck the task box in the to-do list so that you don't forget about it later.

- Finally, I thought the idea was to delete all the maps and the graphs whenever the user closes the application, not when they leave the page. If this is too confusing for you just tell me and I'll do it myself. You would use the `os` module to delete the files sort of like this: [removing files using os](https://linuxize.com/post/python-delete-files-and-directories/). 

- Also , why do you not want to have it in a function? Do you think that it's better coding practice to leave your code floating around outside of a function? That's absolutely wrong. If you're going to run the code more than a couple of times **or** if you want the code to work dynamically, you should put it in a function.

**Comment by Rishbob** [comment]
On the delete function, I meant that I wanted to intergrate it into country_map_generator.py (and the continent map generator when thats ready). If its deleting when the program closes though I can do that.

We'll make sure to clear up the imports when checking it over, most of them were leftovers from faulty builds.
